spring:
    application:
      name: quick-start
    #加载 key 配置文件
    profiles:
      active: key
    ai:
      #deep_seek配置
      deepseek:
        api-key: ${deep-seek.key}
        chat:
          options:
            model: deepseek-chat
      #阿里百炼配置
      dashscope:
        api-key: ${dashscope.key}
        #文本对话
        chat:
          options:
            model: qwen-plus
        #图生文
        image:
          options:
            model: wanx-v1
      #ollama
      ollama:
        base-url: http://localhost:11434
        chat:
          model: qwen2:0.5b
